server:
  port: 8080

# loggin
logging:
  file:
    path: ./logs
  level:
    root: INFO
    com.binchencoder.oauth2: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.boot.autoconfigure: DEBUG

spring:
  application:
    name: workbench-index
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          messaging-client-authorization-code:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/authorized"
            scope:
          messaging-client-client-credentials:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope:
        provider:
          spring:
            authorization-uri: http://auth-server:9000/oauth2/authorize
            token-uri: http://auth-server:9000/oauth2/token
            jwk-set-uri: http://auth-server:9000/oauth2/jwks

messages:
  base-uri: http://localhost:8092/messages
